### ISSUE TITLE
Support Vaadin 8

### ISSUE THREAD

**Issue by bcmedeiros** [willtemperley/v-guice#1]
Error:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.vaadin.server.VaadinServletService.addSessionInitListener(Lcom/vaadin/server/SessionInitListener;)V
	at org.vaadin.addons.guice.servlet.VGuiceApplicationServlet.servletInitialized(VGuiceApplicationServlet.java:48)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:235)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:121)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:220)
```

**Comment by bcmedeiros** [comment]
I'm working to fix that.
